### ISSUE TITLE
Crash upon opening Mods menu

### ISSUE THREAD

**Issue by DroidZed** [TeamMidnightDust/MidnightLib#57]
## Setup:
- Fabric version: 0.92.1+1.20.1
- Minecraft version: 1.20.1
- modmenu: 7.2.2
- midnightlib: 1.4.1-fabric
- Fabric Loader: 0.15.11
- Java: 17
- Language: Kotlin / Fabric Language Kotlin: >=1.11.0+kotlin.2.0.0
- Repo: https://github.com/DroidZed/BuggyMod

## Problem: when I open the mods menu, this error occurs:

<details>
<summary> Logs </summary>

```
[20:49:56] [Render thread/ERROR] (Mod Menu | ModsScreen) Error from mod 'buggymod'
 java.lang.ArrayIndexOutOfBoundsException: null
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77) ~[guava-31.1-jre.jar:?]
	at net.minecraft.client.gui.widget.TabNavigationWidget.selectTab(TabNavigationWidget.java:187) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at eu.midnightdust.lib.config.MidnightConfig$MidnightConfigScreen.<init>(MidnightConfig.java:217) ~[midnightlib-1.4.1-fabric.jar:?]
	at eu.midnightdust.lib.config.MidnightConfig.getScreen(MidnightConfig.java:192) ~[midnightlib-1.4.1-fabric.jar:?]
	at tn.droidzed.buggymod.core.config.ModMenuCompat.getModConfigScreenFactory$lambda$0(ModMenuCompat.kt:13) ~[client/:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:61) ~[modmenu-7.2.2.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.init(ModsScreen.java:114) ~[modmenu-7.2.2.jar:?]
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:297) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient.java:1080) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:15) ~[modmenu-7.2.2.jar:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:94) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:56) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:189) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:38) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.mouseClicked(TitleScreen.java:299) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:98) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:409) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:98) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:169) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102) ~[minecraft-common-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:169) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window.java:288) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1241) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-clientOnly-581a4b72bf-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
```

</details>

**Comment by DroidZed** [comment]
N.B: I also commented out the array variable, still the same !

**Comment by Motschen** [comment]
This only happens when no field annotated with `@Entry` is present in the config class.
Though I can't even seem to find a config class at all in your repo.
